#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Down swap next
riverctl map normal Super+Shift Up swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Right focus-output next
riverctl map normal Super Left focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Right send-to-output next
riverctl map normal Super+Shift Left send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super Comma send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super Period send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super+Shift F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
#riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
#riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
#riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
#riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Media control
riverctl map normal Super F4 spawn 'playerctl play-pause'

# Application binds
riverctl map normal Super L spawn 'loginctl lock-session'
riverctl map normal Super D spawn 'anyrun'
riverctl map normal None Print spawn 'watershot -c directory /home/kirottu/Pictures/Screenshots'
riverctl map normal Super Return spawn alacritty
riverctl map normal Super n spawn 'swaync-client -t'

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x61AFEF
riverctl border-color-unfocused 0x595959

## Input configuration

# Set keyboard repeat rate
riverctl set-repeat 40 300
riverctl keyboard-layout fi

riverctl focus-follows-cursor normal
riverctl hide-cursor when-typing enabled
riverctl hide-cursor timeout 10000

function autostart() {
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    waybar &
    swaybg -i /home/kirottu/Pictures/cursed-harold/1/cursed-harold-big-1080p-bg-forever.png -m fill &
    swayidle -w lock 'swaylock -f' before-sleep 'swaylock -f' &
    swaync &
    /home/kirottu/.cargo/bin/kw-server &
    kidex &
    
    if [ $(hostname) == "church-of-harold" ]; then
        steam &
        discord-ptb --ozone-platform=wayland &
    fi
    
    sleep 2
    udiskie --appindicator -ta &
    nm-applet --indicator &
    nextcloud &
    blueman-applet &

    if [ $(hostname) == "church-of-harold" ]; then
        easyeffects &
        xrandr --output HDMI-A-1 --primary
    fi
}

# Laptop specific configuration
if [ $(hostname) == "missionary-of-harold" ]; then
    # Volume control
    riverctl map normal Super F3 spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%' 
    riverctl map normal Super F2 spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%' 
    riverctl map normal Super F1 spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%' 

    # Backlight control
    riverctl map normal Super+Shift F3 spawn 'light -A 5'
    riverctl map normal Super+Shift F2 spawn 'light -U 5'

    # Touchpad tapping
    riverctl input pointer-1739-52560-SYNA32AC:00_06CB:CD50_Touchpad tap enabled
fi

if [ $(hostname) == "church-of-harold" ]; then
    riverctl map normal Super+Shift S spawn 'systemctl suspend'
    
    # Monitor configuration
    wlr-randr --output DP-3 --mode 1920x1080@60 --pos 0,0
    wlr-randr --output DP-2 --mode 1280x1024@75 --pos 1920,0
    wlr-randr --output HDMI-A-1 --mode 1920x1080@75 --pos 3200,0 --preferred
fi

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

autostart &
