[[language]]
name = "rust"
config.checkOnSave.command = "clippy"

[[language]]
name = "latex"
config.texlab.build.executable = "tectonic"
config.texlab.build.args = [
  "-X",
  "build",
  "--keep-logs",
  "--keep-intermediates"
]
config.texlab.chktex.onOpenAndSave = true
config.texlab.chktex.onEdit = true
config.texlab.build.onSave = true
config.texlab.auxDirecctory = "../build/default"
