[[language]]
name = "rust"

[language-server.rust-analyzer]
config.checkOnSave.command = "clippy"

[language-server.typst-lsp]
command = "typst-lsp"
config = { exportPdf = "onType"}

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []
language-servers = [ "typst-lsp" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { path = "/home/kirottu/git/tree-sitter-typst" }
